kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
data:
  app-config-rhdh.yaml: |
    app:
      title: Super Duper IDP
      baseUrl: https://backstage-developer-hub-rhdh.apps-crc.testing

    auth:
      providers:
        guest:
          dangerouslyAllowOutsideDevelopment: true
            
    backend:
      auth:
        keys:
          - secret: abc123
      baseUrl: https://backstage-developer-hub-rhdh.apps-crc.testing
      cors:
        origin: https://backstage-developer-hub-rhdh.apps-crc.testing
      integrations:
        gitea:
          - host: gitea-scm.apps-crc.testing
            username: ${GITEA_USERNAME}
            password: ${GITEA_PASSWORD}

    argocd:
      waitCycles: 25
      secure: false
      projectSettings:
        # Sets the allowed resources at the cluster level
        clusterResourceWhitelist:
          - group: '*'
            kind: '*'
        # Sets the allowed resources at the namespace level
        namespaceResourceWhitelist:
          - group: '*'
            kind: '*'
      appLocatorMethods:
        - type: 'config'
          instances:
            - name: openshift-gitops
              url: https://openshift-gitops-server-openshift-gitops.apps-crc.testing
              username: ${ARGOCD_ADMIN_USER}
              password: ${ARGOCD_ADMIN_PASSWORD}

    kubernetes:
      clusterLocatorMethods:
        - clusters:
          - authProvider: serviceAccount
            name: ${K8S_CLUSTER_NAME}
            serviceAccountToken: ${K8S_CLUSTER_TOKEN}
            url: ${K8S_CLUSTER_URL}
            skipTLSVerify: true
            skipMetricsLookup: true
          type: config
      customResources:
        - group: 'tekton.dev'
          apiVersion: 'v1beta1'
          plural: 'pipelines'
        - group: 'tekton.dev'
          apiVersion: 'v1beta1'
          plural: 'pipelineruns'
        - group: 'tekton.dev'
          apiVersion: 'v1beta1'
          plural: 'taskruns'
        - group: 'route.openshift.io'
          apiVersion: 'v1'
          plural: 'routes'
      serviceLocatorMethod:
          type: multiTenant
      
